language: node_js
node_js:
  - "10"
  - "12"
  - "node"

jobs:
  include:
  - stage: style
    script: yarn style:check

  - stage: lint
    script: yarn lint

  - stage: deploy
    node_js: '10'
    script: yarn build
    deploy:
      edge: true
      provider: npm
      skip_cleanup: true
      email: mazinsw@gmail.com
      api_key:
        secure: eGqgAA6JQycZgJKAl6irGaPxx4vGXq+lw4176HkPJ0gsBkxvzt7MyupbWzNNGX7GDA9VUU0wlikgPoF7s/xG78wTDpAfDpCMRo8qhfBJ1e/rIWmV+gaGlZ52q99P6K6adj2sCyHXRGmMODh8tQ8g0zdkak/V2U8YD1/0YQbajQGpp93pzl549Rdje6+VSmf43jrMbAatebu6hFQ7nU38kFR/5lwEM42qqp49ktW3No1bWJXuwO+H7GHmOdNFTdHWvId3UkgAQnmi+oFtK+QuOcYtubz6GkmSlnkiC3hhi7jnjqW2CLZKd61yOk83gfHbd/6LrCz6KQo3syFHy9p6421Gj+iA7e9XU3nbMQp9NSQfAFGF+Xs7JTcfFnldzZfovLGgasfHDyGJ0blAnWV0elwwS4EWEyQFrECrMutPWzZg4ISjVRoGBTy4BUG5EaxCLslSK+sMUz4fug7XAKvQ0Kk+FEOgz8H2oaktYzcNSsUXWWbOK5E/gF82vy0hIFTlKymsFzTie/XTQSTs97rKTkW7XlYnzdcDzTsZzo9Vs95zj8LgMY+n4ydmepR1AubCVjsR2BZYtdWyb1lMZFBfYHRo5PcGWB1ANvaC1dWT5mgtmniqF6Yrjk3Lz+EZ5Nb3DzbSfejOTMnQQiZGY+qbaICtAZZqbQltFbFwAudpoVw=
      on:
        tags: true
        repo: grandchef/escpos-template
